name: Irene Iodice
markdown: kramdown

plugins:
  - jekyll-seo-tag

title:	               'Irene Iodice'
description:	       'I am a PhD student in International Economics. Here you
can discover about my research and find material for students in Applied Econometrics'
author:                'Irene Iodice'

url:                   'https://ioire.github.io'
lang:                   en_UK

#social:
#  name: Awesome Author
#  links:


webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
